apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ecommerce-microservices-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: "postgres"
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "ecommerce"
        - name: DB_PASSWORD
          value: "indu1989"
        - name: DB_PORT
          value: "5432"
        - name: JWT_SECRET
          value: "your_super_secret_key_change_this"
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP